def field(label,name,kind='text',help='',**attrs):
    params=' '.join(f'{k}="{escape(str(v),quote=True)}"' for k,v in attrs.items())
    control=f'<textarea id="{name}" name="{name}" rows="4" {params}></textarea>' if kind=='textarea' else f'<input id="{name}" name="{name}" type="{kind}" {params}>'
    return f'<div class="field-group"><label class="field" for="{name}"><span>{label}</span>{control}'+(f'<small>{help}</small>' if help else '')+f'</label><div class="field-ideas" data-for="{name}"></div></div>'
brief=field('Product or collection name','name',required='required',maxlength=140)+field('Who is it for, and when will they use it?','audience','textarea')+field('The experience or practical need','intention','textarea')+field('Chosen Aura expressions or values','expressions',help='Use your own words, separated by commas.')+field('Product details and variants','specification','textarea',help='For example: material, size, format, colour or wording. Keep unknowns visible.')
brief+='''<label class="field"><span>Suggestion direction</span><select name="ideasFocus" id="ideasFocus"><option value="">Follow my product idea</option><option value="clothing">Clothing</option><option value="drinks">Drinks</option><option value="collections">Merchandise and club collections</option><option value="mat">Bathroom mats</option><option value="hygiene">Hygiene and care</option><option value="objects">Everyday objects and gifts</option><option value="gatherings">Gatherings and shared experiences</option></select><small>Usually follows your product name and brief. Choose a direction if another set of ideas would help.</small></label>'''

making=field('Materials, ingredients or components','materials','textarea')+field('Sample or specification version','sampleVersion',help='Give each agreed version a name or date.')+field('Sample observations and next revision','feedback','textarea')
costs=''.join(field(label,name,'number',min=0,step='0.01') for name,label in [('materialsCost','Materials per item (AUD)'),('labourCost','Labour per item (AUD)'),('packagingCost','Packaging per item (AUD)'),('freightCost','Freight per item (AUD)'),('otherCost','Returns, royalties and other per item (AUD)'),('price','Selling price per item (AUD)'),('fixedCost','Fixed setup cost for this batch (AUD)')])+field('Selling fee (%)','feePercent','number',min=0,max=100,step='0.01')+field('Planned units in the batch','quantity','number',min=1,step=1)
offer=field('What does the customer receive?','offer','textarea')+field('Sales route','salesRoute',help='For example: direct, market, hospitality or wholesale.')+field('Availability, timing and handover','fulfilment','textarea')+field('Terms, minimum batch and cancellation approach','terms','textarea')+field('Audience, message and chosen channels','marketing','textarea')+field('Creative assets, credits and agreed use','creative','textarea')
circle=field('Activity and invitation','community','textarea')+field('Participation and sharing choices','participation','textarea')+field('Care, repair or refill route','care','textarea')+field('Receiving service and acceptance conditions','receiver','textarea')+field('Quantity sent into the return process','sent','number',min=0,step='0.01')+field('Quantity received for another use','returned','number',min=0,step='0.01')+field('Unit being measured','unit',help='Use the same unit for both quantities, such as bottles, items or kilograms.')+field('Actual result, losses and operating costs','nextUse','textarea')
agent=field('Task and intended result','agentTask','textarea')+field('Source records and permitted actions','permissions','textarea')+field('Spending and publication limits','limits','textarea')+field('Person handling exceptions','reviewer')+field('Questions to resolve before action','questions','textarea')
tabs=[('brief','The brief',brief),('making','Making',making),('costs','Costs',f'<p>Enter a consistent estimate in AUD. Leave unknown figures blank. This calculator excludes tax and financing and does not verify quotations.</p><div class="form-grid">{costs}</div><div id="cost-results" class="results" aria-live="polite"></div>{field('Cost assumptions and questions','costNotes','textarea',help='Keep quotes, unknown costs and ideas to investigate here. Suggestions do not fill in prices.')}'),('offer','The offer',offer),('circular','Community & next use',circle+'<div id="return-results" class="note" aria-live="polite"></div>'),('connections','Connections','''<p>Connect this record with several people, projects, materials or other products. Each connection describes an exchange; none creates a parent or rank.</p><div id="connections-list"></div><fieldset class="connection-entry"><legend>Add a connection</legend><label class="field">Name<input id="link-name" maxlength="160"></label><label class="field">Contribution or exchange<input id="link-role" maxlength="300"></label><label class="field">Agreed terms or question to resolve<textarea id="link-terms" rows="3"></textarea></label><label class="field">Link to another saved product<select id="link-target"><option value="">No saved product selected</option></select></label><label class="field">Source URL (optional)<input id="link-url" type="url" placeholder="https://"></label><button type="button" class="btn secondary" id="add-connection">Add connection</button></fieldset>'''),('handoff','Agent handoff',agent+'''<label class="field">Permission status<select id="permissionStatus" name="permissionStatus"><option value="draft">Draft only</option><option value="authorised">Scope recorded as authorised</option><option value="paused">Paused</option><option value="revoked">Revoked</option></select></label><p class="note">This prepares a handoff document. No AI agent runs here, and this status does not execute a payment, order, message or publication.</p>''')]
# A recommended route, with every step still available directly.
lookup={key:(label,body) for key,label,body in tabs}
people=field('Maker and dated quotation','maker','textarea',help='Record the actual quote, quantity, inclusions, lead time and source.')+field('People and agreed contributions','contributors','textarea',help='Name the contribution, payment or exchange, and limits of responsibility.')
lookup['connections']=('People & means',people+lookup['connections'][1].replace('<fieldset class="connection-entry">','<details class="more-detail"><summary>Connect a person, project or another product</summary><fieldset class="connection-entry">').replace('</fieldset>','</fieldset></details>'))

def fold_fields(content, names, title):
    """Move related optional fields into a disclosure without changing their IDs."""
    import re
    selected=[]
    for name in names:
        pattern=r'<div class="field-group"><label class="field" for="'+re.escape(name)+r'">.*?</label><div class="field-ideas" data-for="'+re.escape(name)+r'"></div></div>'
        match=re.search(pattern,content,re.S)
        if match:
            selected.append(match.group(0));content=content.replace(match.group(0),'')
    return content+f'<details class="more-detail"><summary>{title}</summary><div>{"".join(selected)}</div></details>'

lookup['brief']=('Your idea',fold_fields(lookup['brief'][1],['expressions','specification'],'Add expressions, variants and finer detail'))
# Direction choice is available with the other optional brief details.
import re
brief_body=lookup['brief'][1]
direction=re.search(r'<label class="field"><span>Suggestion direction</span>.*?</label>',brief_body,re.S).group(0)
lookup['brief']=(lookup['brief'][0],brief_body.replace(direction,'').replace('</details>',direction+'</details>'))
lookup['offer']=('The offer',fold_fields(lookup['offer'][1],['salesRoute','terms','creative'],'Add sales arrangements, terms and creative details'))
lookup['circular']=('Life & next use',fold_fields(lookup['circular'][1],['participation','sent','returned','unit','nextUse'],'Record participation and results from a real trial'))
# Keep measured return feedback with the measurement fields.
lookup['circular']=(lookup['circular'][0],lookup['circular'][1].replace('<div id="return-results" class="note" aria-live="polite"></div>','').replace('</details>','<div id="return-results" class="note" aria-live="polite"></div></details>'))
lookup['handoff']=('Bring it together','<div id="journey-review"></div><details class="more-detail"><summary>Prepare an optional agent handoff</summary><div>'+lookup['handoff'][1]+'</div></details>')
order_keys=['brief','making','connections','costs','offer','circular','handoff']
labels=['Your idea','First sample','People & means','The numbers','The offer','Life & next use','Bring it together']
# Simple original line drawings show what each step is about, not decorative badges.
paths=[
 '<path d="M19 40C8 24 17 10 32 10s24 14 13 30l-5 6H24zM24 53h16M27 59h10"/>',
 '<path d="m12 22 20-11 20 11v25L32 59 12 47zM12 22l20 12 20-12M32 34v25M22 16l20 12v12"/>',
 '<circle cx="32" cy="17" r="7"/><circle cx="13" cy="43" r="7"/><circle cx="51" cy="43" r="7"/><path d="m27 24-10 12m20-12 10 12M20 43h24"/>',
 '<path d="M12 53h42M18 47V33h7v14M30 47V23h7v24M42 47V11h7v36"/>',
 '<path d="M13 25h38l-3 31H16zM23 25v-7a9 9 0 0 1 18 0v7M25 39l5 5 10-12"/>',
 '<path d="M14 30a20 20 0 0 1 34-14l5 6M53 10v12H41M50 36a20 20 0 0 1-34 14l-5-6M11 56V44h12M26 36c0-9 13-14 13-14s3 14-6 18M26 44l10-17"/>',
 '<path d="M16 9h25l9 10v38H16zM40 9v12h10M23 30h20M23 38h20M23 46h12"/>'
]
icons=[f'<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{p}</svg>' for p in paths]
tab_buttons=''.join(f'<button type="button" role="tab" id="tab-{key}" aria-controls="panel-{key}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}" data-tab="{key}"><span class="step-orb">{icons[i]}</span><span>{i+1}. {labels[i]}</span><small class="step-state">Open to explore</small></button>' for i,key in enumerate(order_keys))
panels=''
for i,key in enumerate(order_keys):
    label,content=lookup[key]
    panels+=f'<section class="work-panel" role="tabpanel" id="panel-{key}" aria-labelledby="tab-{key}"'+(' hidden' if i else '')+f'><div class="step-intro"><span class="step-art">{icons[i]}</span><div><p class="step-position">Step {i+1} of 7</p><h2 tabindex="-1" id="step-title-{key}">{labels[i]}</h2><p class="step-lead"></p></div></div><div class="carried-context" id="context-{key}"></div><p class="suggestion-note">Ideas are optional starting points. Use what fits, adapt it or write your own.</p>{content}<aside class="ideas-box" id="ideas-{key}" aria-label="Connected ideas"></aside><div class="step-navigation"><p class="next-thread"></p><div class="actions"><button type="button" class="btn secondary" data-previous="{key}"'+(' hidden' if i==0 else '')+f'>Previous</button><button type="button" class="btn" data-continue="{key}">'+('Save this draft' if i==6 else f'Save & continue to {labels[i+1].lower()}')+'</button></div><p class="journey-save-state" role="status"></p></div></section>'
case_options=''.join(f'<option value="{slug}">{title}</option>' for slug,title,*rest in cases)
start_cards=''.join(f'<button type="button" class="start-card" data-start-case="{key}"><img src="assets/{img}" alt="" loading="lazy"><span><strong>{title}</strong><span>{text}</span></span></button>' for key,img,title,text in [('aura-undies','process.png','Something to wear','Explore comfort, fabric and a personal expression.'),('drinks','workbench-journey.png','Something to share','Develop a drink, a serving and a shared moment.'),('joy-gathering','circular-use.png','Something to bring together','Connect a gathering, its people and continued use.')])
body=f'''<section class="work-head"><div class="wrap work-welcome"><div><h1>One idea.<br>A connected journey.</h1><p>Shape it, try it, connect the people and bring it into everyday life. Each step builds on what you have already explored.</p><a class="btn" href="#work-start">Start or continue <span aria-hidden="true">↓</span></a></div><figure><img src="assets/workbench-journey.png" alt="An imagined product studio where a lavender glass ribbon connects sketches, product samples and a refill garden" width="1536" height="1024" fetchpriority="high"><figcaption>AI-generated concept artwork. From idea to continued use.</figcaption></figure></div></section>
<section class="work-area" id="work-start"><div class="wrap"><div class="work-toolbar"><label class="field">Continue a saved idea<select id="record-select"><option value="">Start a record below</option></select></label><button class="btn secondary" type="button" id="new-record">New blank product</button><label class="field">Explore a case study<select id="case-select"><option value="">Choose a starting idea</option>{case_options}</select></label><button class="btn" type="button" id="open-case">Open case</button></div><div id="app-status" role="status" aria-live="polite">Your work stays in this browser. Save as you go and download a backup to keep it.</div>
<div id="empty-state" class="empty-state"><h2>What would you like to bring to life?</h2><p>Begin with your own idea, or open a case study to see how one idea travels through the whole process.</p><button class="btn" type="button" id="empty-new">Start with my own idea ↗</button><div class="start-cards">{start_cards}</div><p>All nine case studies are available in the selector above.</p></div>
<div id="editor" hidden><div class="record-bar"><div><h2 id="record-heading"></h2><p id="record-meta"></p></div><div class="actions"><button class="btn secondary" type="button" id="save-record">Save record</button><button class="btn secondary" type="button" id="export-pack">Download plan</button></div></div><p id="case-notice" class="note" hidden></p>
<div class="journey-heading"><h3>Your route through the idea</h3><p>Follow the steps or jump to what interests you. Return whenever something changes.</p></div><div class="work-tabs" role="tablist" aria-label="Product journey">{tab_buttons}</div>
<div class="workspace"><aside class="product-thread" aria-label="Your idea so far"><img id="thread-image" src="assets/process.png" alt="AI-generated concept samples on a product workbench"><div><h3 id="thread-name">Your idea so far</h3><p id="thread-intention"></p><div id="thread-notes"></div><p class="thread-foot">One shared draft. Changes here travel with you.</p></div></aside><form id="product-form">{panels}</form></div>
<details class="history"><summary>Saved versions and record details</summary><div id="history-list"></div><div class="record-actions"><button type="button" id="duplicate-record" class="text-button">Duplicate this product</button><button type="button" id="delete-record" class="text-button">Delete this product</button></div></details></div>
<div class="backup-bar"><div><h3>Pick it up again, anywhere.</h3><p>Records stay in this browser on this device. Download a backup to keep another copy or continue in another browser.</p></div><div class="actions"><button class="btn secondary" id="backup" type="button">Download backup</button><label class="btn secondary" for="import-file">Import backup</label><input id="import-file" type="file" accept="application/json,.json" class="sr-only"></div></div></div></section>
<section class="section compact green"><div class="wrap split"><div><h2>A living plan.</h2><p>Samples, conversations and real use can change the idea. Revisit any step and keep learning in the same record.</p></div><div><p>This workbench helps you prepare and connect your plans. Shared accounts, live agents, orders and payments remain future integrations.</p><a href="how-it-works.html">Explore the wider product engine ↗</a></div></div></section>'''
add('workbench.html','Product workbench','Follow one idea through samples, people, costs, offers and continued use in a visual product workbench.',body)
